### PR TITLE
fix: cutted text with content only long text

### LINKED ISSUE #1039: TopTabBar Cropping Labels and different font weight
## Current behavior
 
Top Nav Bar has cropping label and different font from Figma File:

image

## Expected behavior

Should match expected font and not cropping

## How to reproduce it (as minimally and precisely as possible)
 

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

IDE:

- [ ] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Relevant plugins:

### PR DESCRIPTION
**Pull request by Arieldelossantos**
closes #1039

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

with content only tabBar item, if the text is too long, it is cutted off.

## What is the new behavior?

support larger text with may tabs created.

## PR Checklist

Please check if your PR fulfills the following requirements:
- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Tested the changes where applicable:
	- [x] UWP
	- [x] WinUI
	- [ ] iOS
	- [x] Android
	- [ ] WASM
	- [ ] MacOS
- [ ] Updated the documentation as needed:
	- [ ] [General Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc)
	- [ ] [Controls Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc/controls)
	- [ ] [Extensions Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc/helpers)
	- [ ] [controls-styles.md](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls-styles.md)
	- [ ] [lightweight-styling.md (LightWeight Styling Resource Keys)](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/lightweight-styling.md)
- [ ] [Runtime Tests and/or UI Tests](https://platform.uno/docs/articles/contributing/guidelines/creating-tests.html) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal)
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

https://github.com/unoplatform/uno.chefs/issues/937

### CODE REVIEW

**Comment by Arieldelossantos** [comment]
this is an updated branch for the textTrimming issue, for some reason the git index was broken on my side and wasn't updating the other PR branch...

@kazo0 i've added the TextTrimming prop, but it's is still cutting the text if is too long... could this be related to another issue, maybe the container not clipping properly the content? any other idea?

**Comment by kazo0** [comment]
I'm not sure there's too much we can do if the text is too long, if there's no room for the text at a certain point it's going to have to get cut

@Arieldelossantos do you have screenshots of what it looks like when its still getting cut?

**Comment by Arieldelossantos** [comment]
but the thing is that it's not adding the ellipsis on the cutted character :/

there's an error on the runtime test that is blocking me to deploy Android... i think it was introduced on latest main, because i've rebased the branch...
but for this test"ingridients123456789" it will display "ingridients1" with 4 tabs created
@kazo0

**Comment by kazo0** [comment]
@Arieldelossantos ah I believe these TextTrimming property doesn't exist for ContentPresenter? So I'm not sure if there is too much we can do here

**Comment by kazo0** [comment]
@Mergifyio backport release/stable/5.1

**Pull request merged**
