### PR TITLE
fix [TabBar] (#719): Fixes wrong selector offset when switching tabs

### PR DESCRIPTION
**Pull request by lesterbotello**
GitHub Issue (If applicable): #719 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

TabBar selector indicator offset is wrong for slide selection behavior

## What is the new behavior?

TabBar selector indicator is correctly rendered.

## PR Checklist

Please check if your PR fulfills the following requirements:
- [X] Tested code with current [supported SDKs](../README.md#supported)
- [X] Tested the changes where applicable:
	- [X] UWP
	- [X] WinUI
	- [X] iOS
	- [X] Android
	- [X] WASM
	- [ ] MacOS
- [ ] Updated the documentation as needed:
	- [ ] [General Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc)
	- [ ] [Controls Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc/controls)
	- [ ] [Extensions Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc/helpers)
	- [ ] [controls-styles.md](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls-styles.md)
	- [ ] [lightweight-styling.md (LightWeight Styling Resource Keys)](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/lightweight-styling.md)
- [ ] [Runtime Tests and/or UI Tests](https://platform.uno/docs/articles/contributing/guidelines/creating-tests.html) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal)
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
Have you confirmed whether this works on WinUI as well?

**Comment by lesterbotello** [comment]
> Have you confirmed whether this works on WinUI as well?

Yes, works fine on WinUI as well.

**Review by agneszitte — COMMENTED** [review]
@kazo0  I think it would be great if we can add tests for this no ?

**Comment by lesterbotello** [comment]
> @kazo0 I think it would be great if we can add tests for this no ?

Speaking of tests, something I noticed is that the Verify_Indicator_Transition tests are currently failing for TabBar tests, but after my changes they pass (see below), so it looks like something is working :)

Before fix:
SlideTransitions-BeforeFix

After fix:
SlideTransitions-AfterFix

**Comment by kazo0** [comment]
@lesterbotello are those runtime tests failing for WinUI previously? They should be passing for iOS/Android/WASM at least

**Comment by lesterbotello** [comment]
I re-ran the Verify_Indicator_Transition tests on both my branch and on main and the outcome is pretty much the same: The success / failure of this particular tests depends on the height (for the Vertical tab bar test case) or the width (for the Horizontal tab bar test case) available for the rendered tab. When running the tests in a narrow space, the tests usually fail. If you run the tests in a wide screen device in landscape (for example, a tablet), all the test succeed. The same for Windows / WASM if the window is resized accordingly to simulate a narrow / wide device (see screenshots below)
AndroidTablet-Portrait-MenuClosed
AndroidTablet-Portrait-MenuOpen
AndroidTablet-Landscape
WASM-Narrow
WASM-Wide
iOSPhone-Landscape
iOSPhone-Portrait

**Review by kazo0 — COMMENTED** [review]
The logic that is removed here is indeed still needed. Otherwise the selection indicator does not react to the scroll offset of an attached FlipView for ScrollViewer and only reacts to a selection changed


https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/bcc63e9f-ad8f-4bd4-8415-077f9c058de7

**Pull request closed without merging**
