### PR TITLE
refactor: Adjust namespaces for Uno.Material latest package

### PR DESCRIPTION
**Pull request by agneszitte-nventive**
## PR Type

What kind of change does this PR introduce?

- Refactoring (no functional changes, no api changes)

## What is the new behavior?

Adjust namespaces for Uno.Material latest package

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Review by francoistanguay — APPROVED** [review]

**Review by davidjohnoliver — APPROVED** [review]

**Comment by davidjohnoliver** [comment]
image

That's odd, no?

**Review by Xiaoy312 — APPROVED** [review]
just one little thing: remove the 2 unsued xmlns in BottomTabBar.Mobile.xaml

**Comment by Xiaoy312** [comment]
> image
> 
> That's odd, no?

maybe caused by?:
> Pipelines in your region may be impacted by a live site incident, resulting in possible pipeline delays. [Check the status here.](https://status.dev.azure.com/?ref=PipelinesBanner)

**Comment by agneszitte-nventive** [comment]
> just one little thing: remove the 2 unsued xmlns in BottomTabBar.Mobile.xaml

Thank you a lot, removed ;)

**Comment by agneszitte-nventive** [comment]
> > image
> > That's odd, no?
> 
> might be caused by?:
> 
> > Pipelines in your region may be impacted by a live site incident, resulting in possible pipeline delays. [Check the status here.](https://status.dev.azure.com/?ref=PipelinesBanner)

Invalid check due to a change on azure devops, Jerome changed it

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
