### PR TITLE
added non-FrameworkElement support for Responsive-binding

### LINKED ISSUE #950: ResponsiveExpression does not support non-FrameworkElement, like TextBlock>Run
## Current behavior
^ title

## Expected behavior
should be supported

## How to reproduce it (as minimally and precisely as possible)
```xml
<TextBlock Text="{utu:Responsive Normal=ok, Wide=ok}" />
<TextBlock><Run Text="{utu:Responsive Normal=not_ok, Wide=not_ok}" /></TextBlock>
```

## Anything else we need to know?
beside descendants of [`Inline`](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.documents.inline) family, we should probably try to identify more scenarios where this can fail too.

### PR DESCRIPTION
**Pull request by Xiaoy312**
GitHub Issue (If applicable): closes #950

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the new behavior?
added support for non-FrameworkElement responsive-binding without the ResponsiveBehavior.IsEnabled workaround

## PR Checklist

Please check if your PR fulfills the following requirements:
- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [x] Tested the changes where applicable:
	- [ ] UWP
	- [x] WinUI
	- [ ] iOS
	- [ ] Android
	- [x] Skia
	- [ ] WASM
	- [ ] MacOS
- [x] Updated the documentation as needed:
	- [ ] [General Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc)
	- [ ] [Controls Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc/controls)
	- [x] [Extensions Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc/helpers)
	- [ ] [controls-styles.md](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls-styles.md)
	- [ ] [lightweight-styling.md (LightWeight Styling Resource Keys)](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/lightweight-styling.md)
- [ ] [Runtime Tests and/or UI Tests](https://platform.uno/docs/articles/contributing/guidelines/creating-tests.html) for the changes have been added (for bug fixes / features) (if applicable)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Review by carldebilly — APPROVED** [review]

**Comment by Xiaoy312** [comment]
RNG test failures, at least so far it seems:
- https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=2960113&_a=resultQuery
- https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=2960114&_a=resultQuery
- https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=2960109&_a=resultQuery

keep retrying...

**Comment by kazo0** [comment]
@Xiaoy312 since Uno got bumped in this PR, you are hitting [this issue](https://github.com/unoplatform/uno.toolkit.ui/issues/1178)

Should be fixed by [this](https://github.com/unoplatform/uno.toolkit.ui/pull/1182) but that one is also failing the iOS UI tests with timeouts

**Comment by Xiaoy312** [comment]
still failing
flaky?: When_Hug_With_CounterAlignment
requeuing one last time

**Comment by kazo0** [comment]
@Xiaoy312 the failing runtime tests might actually be a valid failure. Since Uno was updated to latest dev in this PR maybe it uncovered a problem with AutoLayout
cc: @carldebilly

**Pull request merged**
