### PR TITLE
fix(autolayout): When SpaceBetween no spacing

### PR DESCRIPTION
**Pull request by Robert-Louis**
GitHub Issue (If applicable): [#1128](https://github.com/unoplatform/Uno.Figma/issues/1128)

## PR Type

What kind of change does this PR introduce?

- Bugfix
## What is the current behavior?

- when in spacebetween the spacing is still use, setting a minimal space between autolayout children

## What is the new behavior?

- when spacebetween the spacing will be ignore

## PR Checklist

Please check if your PR fulfills the following requirements:

- [c] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [c] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [c] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
@Robert-Louis Are you able to add a test ?

**Comment by Robert-Louis** [comment]
@jeromelaban I was planning adding test during the day for various autolayout scenario. I'm not 100% at ease with the runtime so I wanted to take time for this.

**Comment by Robert-Louis** [comment]
@jeromelaban I added the test

**Review by jeromelaban — APPROVED** [review]
And the test is passing :)

**Review by carldebilly — APPROVED** [review]

**Review by Xiaoy312 — APPROVED** [review]

**Pull request merged**
