### PR TITLE
docs: Add TechBites video playlist for TabBar and TabBarItem

### PR DESCRIPTION
**Pull request by agneszitte**
## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## Description

Add TechBites video playlist for TabBar and TabBarItem

### CODE REVIEW

**Comment by agneszitte** [comment]
@Mergifyio backport release/stable/6.0

**Comment by agneszitte** [comment]
I will test the doc locally before putting the PR ready for review

**Comment by morning4coffe-dev** [comment]
@agneszitte Tested the changes in this PR locally and the video playlist seems to work well on my side: 
image

**Review by morning4coffe-dev — APPROVED** [review]

**Comment by agneszitte** [comment]
@Mergifyio backport release/stable/6.0

**Pull request merged**
